version: '3'

services:
  geocoder-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: fanciestw/geocoder:latest
    restart: always
    environment:
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}   # Replace with your Google Maps API key.
      LOGDNA_API_KEY: ${LOGDNA_API_KEY}             # Replace with your logDNA key.
      REDIS_HOST: 10.5.0.7
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      apiNet:
        ipv4_address: 10.5.0.6
    depends_on:
      - geocoder-redis

  geocoder-redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      apiNet:
        ipv4_address: 10.5.0.7

networks:
  apiNet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16